# "Julia"
> "Basics of the julia language"

- author: Christopher Thiemann
- toc: true
- branch: master
- badges: true
- comments: true
- categories: [julia ]
- hide: true
- search_exclude: true

In [ ]:
answer = 43

43

In [ ]:
x = 2

2

In [ ]:
1 < x < 3

true

In [ ]:
M = [1 0; 0 1]

2×2 Array{Int64,2}:
 1  0
 0  1

In [ ]:
typeof(size(M))

Tuple{Int64,Int64}

## Basics

### Assignement

In [ ]:
answer = 42
x, y, z = 1, [1:10; ], "A string" # just like in python !
x, y = y, x # swap x and y

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1)

### Declaring Constants

In [ ]:
const DATE_OF_BIRTH = 2012

2012

### Commenting

In [ ]:
1 + 1 # Hello, this is a comment!

2

### Delimited comment

In [ ]:
1 + #= This comment is inside code! =# 1

2

### Chaining

In [ ]:
x = y = z = 1  # right-to-left

1

In [ ]:
0 < x < 3  #works

true

In [ ]:
z = 10
b = 2
x < y < z < b # works too!

false

### Function definition


In [ ]:
function add_one(i)
    return i + 1 # Just a bit different to python.
end

add_one(2)

3

### Insert LaTeX symbols
Now this is a cool feature...in a code cell type for example \alpha + Tab 

In [ ]:
β = 1

1

## Operators

### Basic Arithmetic 
works as expected

In [ ]:
println(1 + 1)
println(1 - 3)
println(3 * 3)
println(4 / 2)

2
-2
9
2.0


### Exponentiation

In [ ]:
2^2 # note the difference to python 2 ** 2

4

### Remainder

In [ ]:
4 % 3

1

### Negation

In [ ]:
!true # note the difference to numpys ~

false

### Equality

In [ ]:
true == true

true

### Inequality

In [ ]:
true != true

false

### Elementwise operation

In [ ]:
[1 2; 3 3] .* [9 9;9 9] # elementwise

2×2 Array{Int64,2}:
  9  18
 27  27

In [ ]:
[1 2; 3 3] * [9 9;9 9] #matrix materix product

2×2 Array{Int64,2}:
 27  27
 54  54

### Check for nan

In [ ]:
isnan(9)

false

## Ternary operator

The syntax is

cond ? do_true : else

In [ ]:
1 != 1 ? println(3) : println(999)

999


### And/or

In [ ]:
true && true

true

In [ ]:
false || true

true

## Sources

- [ ] https://juliadocs.github.io/Julia-Cheat-Sheet/
- [ ] https://github.com/JuliaLang/julia

- [ ] https://arxiv.org/pdf/2003.10146.pdf

- [ ] https://github.com/h-Klok/StatsWithJuliaBook

- [ ] juliahub

- [ ] juliaacademy

- [ ] https://www.sas.upenn.edu/~jesusfv/Chapter_HPC_8_Julia.pdf

- [ ] https://www.packtpub.com/product/hands-on-design-patterns-and-best-practices-with-julia/9781838648817

- [ ] https://www.elsevier.com/books/introduction-to-quantitative-macroeconomics-using-julia/caraiani/978-0-12-812219-8

- [ ] https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_for_Pythonistas.ipynb#scrollTo=EEzvvzCl1i0F

- [ ] https://cheatsheets.quantecon.org/